auth_enabled: false                    

server:
  http_listen_port: 3100              # Loki listens on this port for HTTP requests (used by Grafana, Promtail)
  grpc_listen_port: 9096              # Loki uses this port internally for gRPC communication between components

common:
  instance_addr: 127.0.0.1            # Localhost binding for internal access only
  path_prefix: /tmp/loki              # Directory to store Loki data (chunks, indexes, etc.)

  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks     # Directory to store compressed log chunks
      rules_directory: /tmp/loki/rules       

  replication_factor: 1              

  ring:
    kvstore:
      store: inmemory                # Use in-memory key-value stor

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true                # Enable query results caching
        max_size_mb: 100             # Limit cache size to 100 MB

schema_config:
  configs:
    - from: 2020-10-24              
      store: boltdb-shipper          # Loki stores index data on disk
      object_store: filesystem       # Store chunks on local file system
      schema: v11                    # internal version Loki uses for organizing data
      index:
        prefix: index_               # Prefix for index files
        period: 24h                  # Create a new index every 24 hours

ruler:
  alertmanager_url: http://localhost:9093   
