name: Docker Compose Actions Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Run Docker Compose on EC2
        run: |
          ssh -v -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navigate to project directory
            cd /home/ec2-user/my_project  # Update this path to your project folder on EC2

            # Run Docker Compose to start services
            docker-compose up -d  # Start the services in the background

            # Verify the services are running
            docker ps  # List the running containers
          EOF
