name: Docker Compose Actions Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Install Docker and Docker Compose on EC2
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Update package list
            sudo apt-get update

            # Install Docker
            sudo apt-get install -y docker.io

            # Enable Docker to start on boot
            sudo systemctl enable docker

            # Start Docker service
            sudo systemctl start docker

            # Install Docker Compose
            sudo apt-get install -y curl
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Verify Docker and Docker Compose installation
            docker --version
            docker-compose --version
          EOF

      - name: Run Docker Compose on EC2
        run: |
          ssh -v -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navigate to project directory
            cd /home/ubuntu/assignment # Update this path to your project folder on EC2

            # Run Docker Compose to start services
            docker-compose up -d  # Start the services in the background

            # Verify the services are running
            docker ps  # List the running containers
          EOF
